# Generated by Django 4.2.5 on 2023-09-27 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("scholar_id", models.CharField(max_length=50)),
                ("affiliation", models.CharField(max_length=200)),
                ("thumbnail", models.CharField(max_length=200)),
                ("interests", models.CharField(max_length=500)),
                ("statistics", models.CharField(max_length=500)),
                ("rank", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=100)),
                ("college", models.CharField(max_length=200)),
                ("school", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "profiles",
                "db_table": "profile",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("year", models.IntegerField()),
                ("citation_id", models.CharField(max_length=100)),
                ("authors", models.CharField(max_length=500)),
                ("journal", models.CharField(max_length=500)),
                ("citations", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "publications",
                "db_table": "publication",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.profile"
                    ),
                ),
                (
                    "publications",
                    models.ManyToManyField(
                        related_name="publications", to="api.publication"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "authors",
                "db_table": "author",
                "ordering": ["profile__name"],
            },
        ),
    ]
