# Generated by Django 4.2.5 on 2023-09-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_publication_authors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
