# Generated by Django 4.2.5 on 2023-09-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_profile_affiliation_alter_profile_college_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="h_index",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="i10_index",
            field=models.IntegerField(default=0),
        ),
    ]
