# Generated by Django 4.2.5 on 2023-10-11 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_profile_h_index_profile_i10_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="h_index",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="i10_index",
        ),
    ]
