# Generated by Django 4.2.5 on 2023-10-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_profile_h_index_remove_profile_i10_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="interests",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="statistics",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
