# Generated by Django 4.2.5 on 2023-10-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_profile_interests_alter_profile_statistics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="interests",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="statistics",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
